### ISSUE TITLE
[BUG] Swampier swamps wants a newer version of Fabric, but there is one problem with this...

### ISSUE THREAD

**Issue by Sunconure11** [andrew0030/SwampierSwamps#12]
https://gist.github.com/Sunconure11/dc63cf9e88d08a27294928e810c3da9a

As you can see, due to the way Quilt works, it currently has some compat issues, thus preventing it from loading.

**Comment by andrew0030** [comment]
My sanity is dwindling at an alarming rate

**Comment by andrew0030** [comment]
That said, I will release a new version ASAP and reduce the required fabric version back to 4.0.9
Should still work the same way as nothing really changed on my end.

**Comment by andrew0030** [comment]
Version 1.19-1.1.2 and newer should work with Quilt.
