### ISSUE TITLE
Feature request: Config value to disable lilypad sinking

### ISSUE THREAD

**Issue by SaimonWoidig** [andrew0030/SwampierSwamps#13]
Despite this being a cool feature, I would like to disable the lilypad sinking feature. But I can only alter the growtime and if they break or become colisionless.

Info:
- Minecraft 1.19.2 with Forge
- Swampier Swamps 1.19-1.1.3

**Comment by andrew0030** [comment]
Hm sounds reasonable, I will add a config option as soon as I have time. I wana finish some other things first but I will add it!

**Comment by SaimonWoidig** [comment]
Wonderful, thanks!

**Comment by andrew0030** [comment]
As of now all latest versions (both fabric and forge) have a Config option to disable Lily Pad sinking.
