### ISSUE TITLE
Question/Request: When the Squad Hops Into Town

### ISSUE THREAD

**Issue by katubug** [andrew0030/SwampierSwamps#14]
Hi! I'm writing quests for my modpack and I've realized I'm not sure whether the vanilla advancement for putting a Lead on all 3 types of Frog is possible, because the other 2 types are disabled? Or am I incorrect, and the modded White and Green frogs count?

Also, I think it would be awesome to have an advancement for putting a Lead on all types of Swampier Swamps frogs!

**Comment by andrew0030** [comment]
I already modified the vanilla advancement to take into account the new variants, it basically now needs you to put all 16 variants on a Lead!
The same goes for getting all Froglights which now also requires you to have all 16 in your Inventory.
If other mods overwrite the jsons for these advancements it may cause them not to work as intended, but it would be an easy fix in form of a datapack!

here is a link to the advancements:
https://github.com/andrew0030/SwampierSwamps/tree/main/src/main/resources/data/minecraft/advancements/husbandry

**Comment by katubug** [comment]
Oh that's perfect! I'm sorry, I should have checked in the jar before I posted. I just woke up so I'm not at 100%. Thank you for the response, and for pre-emptively anticipating this! haha
