### ISSUE TITLE
how do i get the new variants

### ISSUE THREAD

**Issue by catboi101** [andrew0030/SwampierSwamps#16]
I don't know how to use the instructions given and I don't want to mess around with the files incase I mess it up what do I do.

**Comment by catboi101** [comment]
figured it out all i had to do  was make the file a resource

**Comment by EpidemiaOculta** [comment]
How do I get then using commands I mean the frog variants?

**Comment by andrew0030** [comment]
> How do I get then using commands I mean the frog variants?

`/summon minecraft:frog ~ ~ ~ {variant:"swampier_swamps:white_variant"}`
A list of variants can be found [here](https://github.com/andrew0030/SwampierSwamps/blob/main/src/main/java/andrews/swampier_swamps/registry/SSFrogVariants.java).
