### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by tikiMC** [andrew0030/SwampierSwamps#7]
I'm hoping you can tell what's wrong from the crash report.

https://pastebin.com/R3v0MQD3

**Comment by andrew0030** [comment]
So GiantLuigi pointed out to me that this is due a compatibility issue with **[[Smarter Farmers](https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant)]** Basically they use **@Overwrite** on methods I inject code into, as a result my injection cant happen. Think of it like this, when you overwrite something it basically gets replaced, and thus no other Mods can modify it.

I will look into it, maybe I can find some work around. I mean the most obvious solution would be to just not do my mixin if their Mod is loaded, although I have to say I am not really happy with that.

**Comment by andrew0030** [comment]
Ok, so I looked into it and their Mod may use Overwrite but it looks very well made, so I should be able to just not load my mixin, and achieve the same result using their system.

**Comment by tikiMC** [comment]
Thanks for the quick look at it, much appreciated. Your mod looks really cool! Looking forward to playing around with it once the issue is fixed! :D

**Comment by andrew0030** [comment]
Version 1.19-1.1.0 is now available on curse, and this issue has been resolved.
