### ISSUE TITLE
[CRASH] Crash on Quilt Server

### ISSUE THREAD

**Issue by GentlemanCheesy** [andrew0030/SwampierSwamps#9]
**To Reproduce**
Steps to reproduce the crash:
1. Start server with Swampier Swamps.
2. Wait for crash.

**Crash log**
https://pastebin.com/iygyW6NE

**Screenshots**
n/a

**Versions**
Version 1.19-1.1.0
Currently running on quilt 1.19.2-0.17.5-beta6

**Additional context**
Hi there, my quiltmc server is crashing and the logs mention this mod's name within the crash, hopefully I'm just doing something wrong and you might be able to help me fix it. It could potentially be a mod compatibility issue though as I have multiple mods running on the server. Thank you in advance!

**Comment by andrew0030** [comment]
I am not certain what is wrong, but from the looks of it I would say some mod is using a class that isnt available on every system and this causes mixin to blow up, and as a result my mods mixin fail.

[19:56:31] [main/WARN]: Error loading class: org/apache/commons/compress/utils/Lists (java.lang.ClassNotFoundException: org/apache/commons/compress/utils/Lists)
[19:56:31] [main/WARN]: Mixin transformation of net.minecraft.class_4221 failed

**Comment by andrew0030** [comment]
Should be fixed in 1.19-1.1.2 and newer.
